# Generated by Django 5.1.4 on 2024-12-27 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='task_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 27, 15, 0, 23, 557639)),
        ),
    ]
