# Generated by Django 5.1.4 on 2024-12-30 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_task_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
