# Generated by Django 5.1.4 on 2024-12-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
